# render.yaml

services:
  - type: web
    name: autolofi-backend
    env: python
    plan: free # Attention au temps de traitement vidéo sur le plan gratuit
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0