# render.yaml

services:
  - type: web
    name: autolofi-backend
    # 'runtime' est la propriété correcte pour spécifier l'environnement d'exécution.
    runtime: python
    plan: free # Attention : le traitement vidéo peut être lent ou dépasser les limites du plan gratuit.
    
    # Commande pour installer les dépendances avant de démarrer le serveur.
    buildCommand: "pip install -r requirements.txt"
    
    # Commande pour démarrer le serveur web. Gunicorn est recommandé pour la production.
    startCommand: "gunicorn --timeout 300 app:app"
    
    # Définition des variables d'environnement.
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 # Spécifie la version de Python à utiliser.
